//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> CanAddProduct { get; set; }
        public Nullable<bool> CanOrder { get; set; }
        public Nullable<bool> CanCreateInvoice { get; set; }
        public Nullable<bool> CanViewInvoiceDetails { get; set; }
    
        public virtual User User { get; set; }
    }
}
